apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
  namespace: default
  name: Webhook
  description: The Webhook API
  tags:
    - store
    - rest
relations:
  targetref: component/petstore
spec:
  type: openapi
  lifecycle: production
  owner: backstage
  definition:
    $text: https://github.com/faizan2220/webhook_api/blob/main/webhook.yaml
