apiVersion: backstage.io/v1alpha1
kind: API
relations:
  - type: apiProvidedBy
    targetRef: component:default/catstore
  - type: apiProvidedBy
    targetRef: component:default/bottomline
  - type: apiProvidedBy
    targetRef: component:default/saurabh
  - type: apiProvidedBy
    targetRef: component:default/habeeb
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
  namespace: default
  name: Webhook
  description: The Webhook API
  tags:
    - store
    - rest
spec:
  type: openapi
  lifecycle: production
  owner: backstage
  definition:
    $text: https://github.com/faizan2220/webhook_api/blob/main/webhook.yaml
